/* Interactive teaching labs. All datasets are illustrative, not empirical estimates. */
(()=>{const clip=(v,a,b)=>Math.max(a,Math.min(b,v)), fmt=v=>Number(v).toFixed(2), phi=z=>Math.exp(-z*z/2)/Math.sqrt(2*Math.PI);
const Phi=z=>{let x=Math.abs(z),t=1/(1+.2316419*x),p=1-phi(x)*t*(.31938153+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));return z>=0?p:1-p};
const defs={
taste:{x:[0,40],y:[-20,25],xl:'Taste cost t',yl:'Subjective surplus',params:[['t','Taste cost',0,40,12,1]],curves:v=>[{color:'#0b6d69',fn:x=>20-x}],point:v=>[v.t,20-v.t],read:v=>`Financial surplus stays 20. Subjective surplus: ${fmt(20-v.t)}. ${v.t<20?'Hire':v.t>20?'Reject':'Indifferent'}.`,drag:'t'},
signal:{x:[0,1],y:[55,85],xl:'Reliability λ',yl:'Predicted productivity',params:[['lambda','Reliability λ',0,1,.4,.01]],curves:v=>[{color:'#0b6d69',fn:x=>60+20*x},{color:'#b65335',fn:x=>70+10*x}],point:v=>[v.lambda,60+20*v.lambda],read:v=>`Teal: ${fmt(60+20*v.lambda)}; orange: ${fmt(70+10*v.lambda)}. Gap: ${fmt(10*(1-v.lambda))}.`,drag:'lambda'},
testing:{x:[0,.3],y:[-200,300],xl:'Pass probability p',yl:'Expected value ($000)',params:[['p','Pass rate p',0,.3,.05,.005],['c','Test cost ($000)',20,200,100,5]],curves:v=>[{color:'#0b6d69',fn:x=>1000*x-v.c}],point:v=>[v.p,1000*v.p-v.c],read:v=>`Expected net value: $${fmt(1000*v.p-v.c)}k. Break-even pass rate: ${fmt(v.c/10)}%.`,drag:'p'},
probability:{x:[0,10],y:[0,1],xl:'Own effort E₁',yl:'Winning probability',params:[['own','Own effort E₁',0,10,4,.1],['rival','Rival effort E₂',0,10,4,.1],['alpha','Precision α',.02,.25,.1,.01]],curves:v=>[{color:'#0b6d69',fn:x=>clip(.5+v.alpha*2*(x-v.rival),0,1)}],point:v=>[v.own,clip(.5+v.alpha*2*(v.own-v.rival),0,1)],vertical:v=>v.rival,read:v=>`d = 2. p₁ = ${fmt(clip(.5+v.alpha*2*(v.own-v.rival),0,1))}. Interior slope = ${fmt(v.alpha*2)}.`,drag:'own'},
utility:{x:[0,12],y:[-65,35],xl:'Own effort E',yl:'Expected utility',params:[['own','Own effort',0,12,4,.1],['S','Prize spread S',0,40,10,.5],['rival','Rival effort',0,10,4,.1]],curves:v=>[{color:'#0b6d69',fn:x=>9+clip(.5+.1*2*(x-v.rival),0,1)*v.S-x*x/2}],point:v=>[v.own,9+clip(.5+.2*(v.own-v.rival),0,1)*v.S-v.own*v.own/2],read:v=>{let best=0,b=-Infinity;for(let e=0;e<=12;e+=.01){let u=9+clip(.5+.2*(e-v.rival),0,1)*v.S-e*e/2;if(u>b){b=u;best=e}}return `a = 9, α = 0.1, d = 2. Interior candidate: ${fmt(.2*v.S)}. Approx. global best effort: ${fmt(best)}; max utility: ${fmt(b)}.`},drag:'own'},
risk:{x:[.3,8],y:[0,1],xl:'Relative noise σ',yl:'Winning probability',params:[['sigma','Relative noise σ',.3,8,2,.1],['gap','Mean gap Δ',-6,6,-2,.1]],curves:v=>[{color:'#0b6d69',fn:x=>Phi(v.gap/x)}],point:v=>[v.sigma,Phi(v.gap/v.sigma)],read:v=>`Δ = ${fmt(v.gap)}. p(win) = ${fmt(Phi(v.gap/v.sigma))}. More risk ${v.gap<0?'helps the trailer':v.gap>0?'hurts the leader':'leaves p at 1/2'}.`,drag:'sigma'},
handicap:{x:[0,8],y:[0,1],xl:'Handicap h',yl:'Probability / local slope',params:[['h','Handicap h',0,8,0,.1],['gap','Advantage Δ',0,8,4,.1]],curves:v=>[{color:'#0b6d69',fn:x=>Phi((v.gap-x)/2)},{color:'#b65335',fn:x=>phi((v.gap-x)/2)/2}],point:v=>[v.h,Phi((v.gap-v.h)/2)],read:v=>`σ = 2, d = 1. Teal p = ${fmt(Phi((v.gap-v.h)/2))}; orange slope = ${fmt(phi((v.gap-v.h)/2)/2)}. Slope peaks at h = Δ.`,drag:'h'},
entry:{x:[0,1],y:[-15,32],xl:'Perceived probability p̂',yl:'Certainty equivalent',params:[['p','Perceived chance p̂',0,1,.6,.01],['rho','Risk aversion ρ',0,.15,.04,.005]],curves:v=>[{color:'#0b6d69',fn:x=>30*x-v.rho*.5*x*(1-x)*900},{color:'#b65335',fn:x=>12}],point:v=>[v.p,30*v.p-v.rho*.5*v.p*(1-v.p)*900],read:v=>{let ce=30*v.p-v.rho*.5*v.p*(1-v.p)*900;return `Approximate CE = ${fmt(ce)}; safe payoff = 12. ${ce>=12?'Choose tournament':'Choose safe pay'}. True success probability may differ.`},drag:'p'}
};
window.__labDefs=defs;
document.querySelectorAll('.lab').forEach(el=>{let d=defs[el.dataset.lab],v=Object.fromEntries(d.params.map(p=>[p[0],p[4]]));el.innerHTML=`<svg viewBox="0 0 900 440" role="img" aria-label="Interactive graph: ${d.yl} against ${d.xl}"></svg><div class="controls"></div><div class="readout" aria-live="polite"></div><p class="hint">Drag the large dot or use the sliders. <button class="reset">Reset</button></p>`;
let svg=el.querySelector('svg'),ctrl=el.querySelector('.controls');d.params.forEach(([key,label,min,max,value,step])=>{let box=document.createElement('div');box.className='control';box.innerHTML=`<label>${label}: <output>${value}</output><input aria-label="${label}" data-key="${key}" type="range" min="${min}" max="${max}" value="${value}" step="${step}"></label>`;ctrl.append(box);box.querySelector('input').addEventListener('input',e=>{v[key]=+e.target.value;draw()})});
const X=x=>90+(x-d.x[0])/(d.x[1]-d.x[0])*740,Y=y=>355-(y-d.y[0])/(d.y[1]-d.y[0])*285;
function draw(){let a=`<defs><clipPath id="clip-${el.id}"><rect x="90" y="70" width="740" height="285"/></clipPath></defs>`;for(let i=0;i<=4;i++){let x=d.x[0]+i*(d.x[1]-d.x[0])/4,y=d.y[0]+i*(d.y[1]-d.y[0])/4;a+=`<path d="M ${X(x)} 70 V355 M90 ${Y(y)} H830" stroke="#dce4de"/><text x="${X(x)}" y="390" text-anchor="middle">${+x.toFixed(2)}</text><text x="75" y="${Y(y)+8}" text-anchor="end">${+y.toFixed(2)}</text>`}a+=`<path d="M90 70 V355 H830" stroke="#29434b" fill="none" stroke-width="2"/><text x="460" y="432" text-anchor="middle">${d.xl}</text><text x="90" y="32">${d.yl}</text>`;if(d.y[0]<0&&d.y[1]>0)a+=`<path d="M90 ${Y(0)} H830" stroke="#738b84" stroke-dasharray="6 6"/>`;if(d.vertical)a+=`<path d="M${X(d.vertical(v))} 70 V355" stroke="#b65335" stroke-dasharray="6 6"/>`;for(let c of d.curves(v)){let path='';for(let i=0;i<=200;i++){let x=d.x[0]+i/200*(d.x[1]-d.x[0]);path+=(i?'L':'M')+X(x)+','+Y(c.fn(x))}a+=`<path clip-path="url(#clip-${el.id})" d="${path}" fill="none" stroke="${c.color}" stroke-width="5"/>`}let p=d.point(v);a+=`<circle class="drag-point" cx="${X(p[0])}" cy="${Y(p[1])}" r="14" fill="#c98b45"/><circle cx="${X(p[0])}" cy="${Y(p[1])}" r="27" fill="transparent" class="drag-hit" style="cursor:grab"/>`;svg.innerHTML=a;el.querySelector('.readout').textContent=d.read(v);ctrl.querySelectorAll('input').forEach(n=>{n.value=v[n.dataset.key];n.parentNode.querySelector('output').textContent=+v[n.dataset.key].toFixed(3)});el.dataset.values=JSON.stringify(v)}
let dragging=false;svg.addEventListener('pointerdown',e=>{if(e.target.matches('.drag-point,.drag-hit')){dragging=true;svg.setPointerCapture(e.pointerId);e.preventDefault()}});svg.addEventListener('pointermove',e=>{if(!dragging)return;let point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;let local=point.matrixTransform(svg.getScreenCTM().inverse()),param=d.params.find(p=>p[0]===d.drag);v[d.drag]=clip(d.x[0]+(local.x-90)/740*(d.x[1]-d.x[0]),param[2],param[3]);draw()});svg.addEventListener('pointerup',()=>dragging=false);svg.addEventListener('pointercancel',()=>dragging=false);el.querySelector('.reset').onclick=()=>{d.params.forEach(p=>v[p[0]]=p[4]);draw()};draw();
});})();
