"""Build map/PRIORITIES.md: exam weight x difficulty x readiness -> where study hours pay off most.

Usage (from the repo root):
  python tools/priorities.py            use the default readiness below (owner's status, 5 Oct 2026)
  python tools/priorities.py <name>     derive readiness from progress/<name>.md (avg confidence per topic)

Inputs: map/GAPS-PUBLIC.md, map/GAPS-PERSONNEL.md (weight, hours, gap verdict),
        map/_work/difficulty-public.md, map/_work/difficulty-personnel.md (D1-D5, composite).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "map"

# Readiness gap: 1.0 = not started / not yet taught, 0.8 = half done or never trained,
# 0.6 = done once but the exam variant isn't trained, 0.5 = done once. Edit as you progress,
# or pass a name to use your progress file instead.
DEFAULT_GAP = {
    "PUB-TAX-INC": 0.8, "PUB-TAX-EB": 0.8, "PUB-TAX-PROG": 0.8, "PUB-CBA": 0.6,
    "PUB-TAX-RAMSEY": 1.0, "PUB-TAX-MCPF": 1.0, "PUB-TAX-OPTINC": 1.0,
    "PUB-POL-VOTE": 1.0, "PUB-POL-GOVFAIL": 1.0,
    "PUB-POSNORM": 0.8, "PUB-EXT-INSTR": 0.8, "PUB-REDIST-PROG": 0.6, "PUB-WELF": 0.6, "PUB-SWF": 0.6,
    "PER-TOURN": 1.0, "PER-TEAM": 1.0, "PER-BIAS": 1.0,
    "PER-NONCLASS": 0.6, "PER-EMP": 0.6, "PER-MONOPSONY": 0.6, "PER-INCOME": 0.6,
}
DEFAULT_DONE_ONCE = 0.5


def table_rows(path):
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("|") and not re.match(r"^\|\s*-", line):
            yield [c.strip() for c in line.strip().strip("|").split("|")]


def load():
    topics = {}
    for fn in ["GAPS-PUBLIC.md", "GAPS-PERSONNEL.md"]:
        for c in table_rows(MAP / fn):
            m = re.match(r"^\[?((?:PUB|PER)-[A-Z0-9-]+)\]?", c[0])
            if not m or len(c) < 6:
                continue
            pct = re.findall(r"([\d.]+)%", c[2])
            hours = re.findall(r"[\d.]+", c[-1])
            topics[m.group(1)] = {
                "prio": c[1].replace("*", "").split()[0] if c[1] else "",
                "weight": float(pct[-1]) if pct else 0.0,
                "verdict": re.sub(r"\*", "", c[3]),
                "hours": float(hours[0]) if hours else 1.0,
                "file": fn,
            }
    for fn in ["difficulty-public.md", "difficulty-personnel.md"]:
        for c in table_rows(MAP / "_work" / fn):
            m = re.match(r"^\[?((?:PUB|PER)-[A-Z0-9-]+)", c[0])
            if m and len(c) >= 8 and m.group(1) in topics:
                t = topics[m.group(1)]
                t["d"] = [float(x) for x in c[1:6]]
                t["diff"] = float(c[6].replace("*", ""))
                t["why"] = c[7]
                t["dfile"] = fn
    return {k: v for k, v in topics.items() if "diff" in v}


def readiness_from_progress(name):
    path = ROOT / "progress" / f"{name}.md"
    scores = {}
    for c in table_rows(path):
        if len(c) >= 6 and re.match(r"^\d$", c[3]):
            for t in re.findall(r"(?:PUB|PER)-[A-Z0-9-]+[A-Z0-9]", c[1]):
                scores.setdefault(t, []).append(int(c[3]))
    return {t: round(1 - (sum(v) / len(v)) / 3, 2) for t, v in scores.items()}


def quadrant(t):
    if t["weight"] == 0:
        return "⚪ Skim"
    hi_w, hi_d = t["weight"] >= 2.5, t["diff"] >= 3.0
    return {(True, True): "🔴 Critical", (True, False): "🟢 Bank",
            (False, True): "🟠 Contain", (False, False): "⚪ Skim"}[(hi_w, hi_d)]


def link(tid):
    return f"[{tid}](topics/{tid}.md)"


def main():
    who = sys.argv[1] if len(sys.argv) > 1 else None
    gap = readiness_from_progress(who) if who else {}
    T = load()
    for tid, t in T.items():
        t["gap"] = gap.get(tid, DEFAULT_GAP.get(tid, DEFAULT_DONE_ONCE)) if who else DEFAULT_GAP.get(tid, DEFAULT_DONE_ONCE)
        t["risk"] = round(t["weight"] * t["diff"] / 5 * t["gap"], 2)
        t["roi"] = round(t["risk"] / max(t["hours"], 0.25), 2)
        t["q"] = quadrant(t)

    by_roi = sorted(T, key=lambda k: (-T[k]["roi"], -T[k]["risk"]))
    by_diff = sorted(T, key=lambda k: (-T[k]["diff"], -T[k]["weight"]))
    by_risk = sorted(T, key=lambda k: -T[k]["risk"])
    src = f"progress/{who}.md" if who else "default status (5 Oct 2026)"
    o = []
    o += ["# Priorities - weight x difficulty x readiness", "",
          f"_Generated by `python tools/priorities.py{' ' + who if who else ''}` from the gap tables and difficulty scores. Readiness source: {src}. Re-run after updating your progress file._", "",
          "**How to read it**",
          "- **Weight** = average % of a final/resit this topic is worth (4 papers).",
          "- **Difficulty** = 1-5, mean of math load, conceptual traps, verbal precision, variability between exams, and tutorial gap (rubric: [Public](_work/difficulty-public.md), [Personnel](_work/difficulty-personnel.md)).",
          "- **Readiness gap** = 1.0 not started / not yet taught ... 0.5 done once ... 0 solved cold.",
          "- **Points at risk** = weight x difficulty/5 x readiness gap = expected % of the exam you'd lose today.",
          "- **ROI** = points at risk per study hour. **Work top-down on ROI.**", "",
          "## 1. Work order (best return per hour first)", "",
          "| # | Topic | Part | Quadrant | Weight | Difficulty | Gap | Points at risk | Hours | ROI |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for i, k in enumerate([k for k in by_roi if T[k]["risk"] > 0], 1):
        t = T[k]
        o.append(f"| {i} | {link(k)} | {k[:3]} | {t['q']} | {t['weight']}% | {t['diff']} | {t['gap']} | **{t['risk']}%** | {t['hours']} | {t['roi']} |")
    total = sum(t["risk"] for t in T.values())
    o += ["", f"Total points at risk today: **{total:.1f}% of the exam**, spread across {sum(1 for t in T.values() if t['risk'] > 0)} examined topics.", ""]

    o += ["## 2. The matrix", "",
          "| | **Easier (difficulty < 3)** | **Harder (difficulty ≥ 3)** |", "|---|---|---|"]
    def cell(qn):
        return ", ".join(f"{link(k)} ({T[k]['weight']}%, d{T[k]['diff']})" for k in by_risk if T[k]["q"] == qn) or "-"
    o.append(f"| **High weight (≥ 2.5%)** | 🟢 **Bank** - learnable points you must not drop: {cell('🟢 Bank')} | 🔴 **Critical** - most points and hard: {cell('🔴 Critical')} |")
    o.append(f"| **Low weight (< 2.5%)** | ⚪ **Skim** (examined, low weight): " + ", ".join(link(k) for k in by_risk if T[k]["q"] == "⚪ Skim" and T[k]["weight"] > 0) + f" | 🟠 **Contain** - learn the template, don't over-invest: {cell('🟠 Contain')} |")
    o += ["", "Never examined (0%): " + ", ".join(link(k) for k in sorted(T) if T[k]["weight"] == 0) + " - skim only.", ""]

    o += ["## 3. Hardest topics (difficulty ranking)", "",
          "| # | Topic | Difficulty | Math | Traps | Verbal | Variability | Tut. gap | Weight | Why it's hard |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for i, k in enumerate(by_diff[:15], 1):
        t = T[k]
        d = " | ".join(str(int(x)) for x in t["d"])
        o.append(f"| {i} | {link(k)} | **{t['diff']}** | {d} | {t['weight']}% | {t['why']} |")
    o += ["", "Full reasoning, typical point losses and \"crack it by\" actions per topic: "
          "[difficulty-public.md](_work/difficulty-public.md), [difficulty-personnel.md](_work/difficulty-personnel.md).", ""]

    o += ["## 4. Most points (weight ranking)", "",
          "| # | Topic | Weight | Prio | Gap verdict | Difficulty |", "|---|---|---|---|---|---|"]
    for i, k in enumerate(sorted(T, key=lambda k: -T[k]["weight"])[:15], 1):
        t = T[k]
        o.append(f"| {i} | {link(k)} | {t['weight']}% | {t['prio']} | {t['verdict']} | {t['diff']} |")
    o += ["", "## Caveats", "",
          "- Weights split each sub-question's points across its tags, so cross-cutting skills look smaller than they are. **PUB-POSNORM** (normative vs positive one-liners) is only 0.9% on paper, but it is the most common 0 in the grading schemes and sits inside Coase, SWF and voting questions.",
          "- **One-off blocks** (teams, commons, tournaments, welfare programmes) have an average weight that hides their size. When one appears, it is 15-19% of that paper, and every paper had 1-2 of them.",
          "- Upcoming topics (tournaments, teams, Ramsey, voting) have gap = 1.0 until you've done their lecture and exercise set. Their difficulty also drops once the sets are released (tutorial gap D5 falls), so re-run this after 16 Oct.",
          "- \"Points at risk\" is a ranking device, not a grade prediction."]
    (MAP / "PRIORITIES.md").write_text("\n".join(o) + "\n", encoding="utf-8")
    print(f"PRIORITIES.md: {len(T)} topics, {total:.1f}% at risk; top 5 ROI:", by_roi[:5])


if __name__ == "__main__":
    main()
